import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

import Head from "next/head";


const MainLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Taichi Health & Beauty Center</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div id="mainContainer">{children}</div>
      <Footer />
    </>
  );
};

export default MainLayout;
